### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by Shentia** [emmetio/pyv8-binaries#31]
hello dear friends 
I cant download https://github.com/emmetio/pyv8-binaries/blob/master/pyv8-win64-p3.zip this link 
I am from Iran 
I need this file.

**Comment by QiyaoShn** [comment]
me too!

**Comment by sergeche** [comment]
You can try new Emmet 2 plugin which doesn’t require this file: https://github.com/emmetio/sublime-text-plugin
